name: dslink_dgapi
version: 1.0.1
description: DSLink for compatibility with the old DGAPI.
environment:
  sdk: ">=1.0.0 <2.0.0"
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  http: "^0.11.3+2"
  crypto: "^2.0.1"