name: dslink_dgapi
version: 0.0.1
description: DSLink for Compatibility with the old DGAPI.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  crypto: any
  dslink:
    git:
      url: git://github.com/IOT-DSA/sdk-dslink-dart.git
      ref: "333014fd04726cf03284a635c558fbc42a706b37"
